### ISSUE TITLE
Suggestion: Subregion priority change

### ISSUE THREAD

**Issue by cantorthiagofelipe** [alex9849/advanced-region-market#108]
Subregions are created on the same priority of a region. it would be better if there was an option in the config to change the default priority, and also, a flag to insert a custom priority in a preset, or automatically increase 1 point in the priority of the created subregion

changing subregions priority manually is very bad

**Comment by alex9849** [comment]
There is an option in your config.yml. This one: `allowParentRegionOwnersBuildOnSubregions`
If it's set to `true` the parent region will be set as parent region in Workdguard. If not the priority of the subregion gets automatically set to 1 above the priority of the parent region.

**Comment by cantorthiagofelipe** [comment]
> There is an option in your config.yml. This one: `allowParentRegionOwnersBuildOnSubregions` If it's set to `true` the parent region will be set as parent region in Workdguard. If not the priority of the subregion gets automatically set to 1 above the priority of the parent region.

I'll try it. Thanks!
