### ISSUE TITLE
ARM going nuclear and taking server with FAWE

### ISSUE THREAD

**Issue by Chocolate1Donut** [alex9849/advanced-region-market#111]
First off, thanks for developing a badass plugin. Works flawlessly. 

But recently when a plot expired for the first time on our server, it seems ARM went crazy and took the server down with it.

I understand FAWE is kind of sketchy for other plugin support, but maybe there is something I am missing as having to return to synchronous WorldEdit on a server that heavily relies on terraforming would suck.

If it's not in your control don't hesitate to let me know so I can nag FAWE devs about it :)

Java 17 (OpenJDK 64-Bit Server VM 17.0.2+8-86) Host: Linux 5.4.0-94-generic (amd64)
Paper-379 (MC: 1.18.2)

Log: https://pastebin.com/zkXLtW1R

**Comment by alex9849** [comment]
I can only fix problems that have been caused by arm. Arm uses worldedit to create and restore schematics. It looks like your fawe/worldedit version is incompatible with your server version. Your problem should be solvable by updating worldedit to a compatible version. :)
