### ISSUE TITLE
Missing config.yml option activateRegionKindPermissions

### ISSUE THREAD

**Issue by Roos-Skywalker** [alex9849/advanced-region-market#115]
According to the [documentation about the config.yml](https://github.com/alex9849/advanced-region-market/wiki/config.yml) a section called RegionKinds should exist. It should look like this:
```
RegionKinds:
  activateRegionKindPermissions: false
```
Is this intentional? What happened to it?
I manually added the whole section to my config.yml without parsing errors but it does not seem to take effect when set to true. #

**Comment by alex9849** [comment]
It looks like this part of the documentation is outdated. I'll remove it. The limit-system can be used to do that. These regionkind permissions have been redundant and got removed.

**Comment by Roos-Skywalker** [comment]
Thank you for your quick response!
A reference to this missing documentation still exists [here](https://github.com/alex9849/advanced-region-market/wiki/regionkinds.yml)
