### ISSUE TITLE
Regionkind Groups

### ISSUE THREAD

**Issue by alex9849** [alex9849/advanced-region-market#12]
Regionkind should be made groupable. For example it should be possible to group two regionkinds citybuild_small and citybuild_medium together to a group named citybuild.

The limitgroup feature should be expanded to allow admins to limit buyable regions per regionkind-group. This way players could decide how they want to allocate their regionlimits. For example if you set the grouplimit for the citybuild group to 5, players should be able to buy for example 2 citybuild_medium plots and 3 citybuild_small plots.

The /arm info commands needs to display to which group a regionkind belongs. 
One possible way would be: RegionKind: citybuild_small (Citybuild)

**Comment by kikelkik** [comment]
I already made a fork for this enhancement.
Already works good for these groups but the config should be capable to also represent limits the old way to stay compatible to existing server configurations, right?

**Comment by alex9849** [comment]
Implemented
