### ISSUE TITLE
Add ability for owners to clear regions

### ISSUE THREAD

**Issue by doitliketyler** [alex9849/advanced-region-market#120]
Would be nice to allow owners/members to clear a region of all blocks via command & GUI. I checked to see if this feature already exists and didn't see anything. Any chance you would add this? Thanks in advance.

Command: /arm clear [REGION]
Permission: arm.member.clear

**Comment by Roos-Skywalker** [comment]
Sounds like /arm reset [REGION]
This command (which doesn't run from console for some reason) sets the chosen region back to its previous state and reapplies the original schematic file if there is one.

**Comment by doitliketyler** [comment]
No that command does exactly what it's meant todo which is reset the region to default. I'm asking for a command that clears the region of all blocks. It's not the same.

**Comment by alex9849** [comment]
You can use /arm restore for that. There is also a member permission and a cooldown integrated so this feature won't get abused.

**Comment by doitliketyler** [comment]
Nope...that also resets the region to default which is not what I'm asking for. I would like to be able to clear the region completely...no blocks on it from placement or from a schematic. Its not the same as reset or restore which I tried both prior to posting this.

**Comment by alex9849** [comment]
OK? So you just want to remove everything including the bedrock?

**Comment by doitliketyler** [comment]
Just clear everything that's in the region no matter what the block is. Something as simple as selecting the region and setting all blocks to air would work.

For context, I have player shop regions that come with optional pre-built shops on the regions. The regions aren't hotels so they can use the pre-built or tear it down and build their own custom shop. Would be a nice QoL update to allow them to just clear the plot if they don't want to use the pre-built vs always having to tear it down. Hope this helps.

**Comment by Roos-Skywalker** [comment]
In that case just use Luckperms with Extra Contexts so you can give worldedit permission on per region basis. When leaving the region the permission is removed.

**Comment by doitliketyler** [comment]
I know that’s possible but Im not going to do that. It’s not easy for the
players to remember random commands like that and it’s unprofessional. What
I’m asking is not out of scope for this plugin and would be a nice
addition. There is also an available slot in the GUI. Please add a simple
region clear option.

**Comment by Roos-Skywalker** [comment]
You can add an alias to any command without additional plugins simply by registering an alias in the commands.yml file of the server. You can copy paste this and be done. However, the player would still need to select the region with `/rg select`
`aliases:
  icanhasbukkit:
  - version $1-
  clearshop:
  - /set air $1`
