### ISSUE TITLE
Bad jitpack.io artifact

### ISSUE THREAD

**Issue by Ghost-chu** [alex9849/advanced-region-market#122]
Hi alex!
I'm looking for ARM integration in QuickShop-Hikari, and when I pull ARM from jitpack.io as a dependency, jitpack seems just returns a incomplete and broken artifacts like this:
![image](https://user-images.githubusercontent.com/30802565/189475215-62b97150-def2-48fb-8957-2021e1a985ea.png)
![image](https://user-images.githubusercontent.com/30802565/189475222-0a5f6dc0-722e-41e0-8265-2d8eeeeb6df5.png)

This is my pom.xml:

```xaml
	<dependency>
	    <groupId>com.github.alex9849.advanced-region-market</groupId>
	    <artifactId>arminterface</artifactId>
	    <version>3.4.1</version>
            <scope>provided
	</dependency>
```

**Comment by alex9849** [comment]
Normally you should use advanced-region-market as an artifact. Like this:
`<dependency>
	    <groupId>com.github.alex9849</groupId>
	    <artifactId>advanced-region-market</artifactId>
	    <version>3.4.1</version>
	</dependency>`

I don't think that it also works if you only use the interface.

**Comment by Ghost-chu** [comment]
> Normally you should use advanced-region-market as an artifact. Like this:
> 
> ```
>        <dependency>
> 	    <groupId>com.github.alex9849</groupId>
> 	    <artifactId>advanced-region-market</artifactId>
> 	    <version>3.4.1</version>
> 	</dependency>
> ```
> 
> I don't think that it also works if you only use the interface.

sorry for bad paste!

actually is 
```xaml
	<dependency>
	    <groupId>com.github.alex9849</groupId>
	    <artifactId>advanced-region-market</artifactId>
	    <version>2.1.5</version>
	</dependency>
```
I have pasted wrong code on issue

**Comment by Ghost-chu** [comment]
> > Normally you should use advanced-region-market as an artifact. Like this:
> > ```
> >        <dependency>
> > 	    <groupId>com.github.alex9849</groupId>
> > 	    <artifactId>advanced-region-market</artifactId>
> > 	    <version>3.4.1</version>
> > 	</dependency>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't think that it also works if you only use the interface.
> 
> sorry for bad paste!
> 
> actually is
> 
> ```
> 	<dependency>
> 	    <groupId>com.github.alex9849</groupId>
> 	    <artifactId>advanced-region-market</artifactId>
> 	    <version>2.1.5</version>
> 	</dependency>
> ```
> 
> I have pasted wrong code on issue

This dependency offers interface and adapters and advanced-region-market artifact (but most likely empty, only META-INF inside)

**Comment by alex9849** [comment]
OK. I have to look into that. But I can do this only tomorrow. Does this also happen with other versions?

**Comment by Ghost-chu** [comment]
fast check the version 3.3.6 also doesn't work.

```xaml
        <dependency>
            <groupId>com.github.alex9849</groupId>
            <artifactId>advanced-region-market</artifactId>
            <version>3.3.6</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by alex9849** [comment]
Ok I found the problem. Jitpack compiled the project with an unsupported java version. You should now be able to use the 3.4.1 tag.
