### ISSUE TITLE
permission for /arm sellback

### ISSUE THREAD

**Issue by kikelkik** [alex9849/advanced-region-market#14]
Hey,
I recognized a conflict between the [documentation](https://github.com/alex9849/advanced-region-market/wiki/Commands-and-permissions) and how the plugin actually works.

The docu says that /arm sellback has the permission arm.member.sellback .
But ingame that permission doesn't exist. 
The code gives a hint for arm.member.sellregion being used instead. In my opinion, arm.member.sellback is a way better choice due to naming simplicity.
https://github.com/alex9849/advanced-region-market/blob/196ad713b9a5ac891a0c6439cd47f78754ff2676/advancedregionmarket/src/main/java/net/alex9849/arm/Permission.java#L118

**Comment by alex9849** [comment]
Fixed :)
