### ISSUE TITLE
Polygonal selections have no price

### ISSUE THREAD

**Issue by Bloodlex** [alex9849/advanced-region-market#144]
Hey,

After creating polygonal selection with WorldEdit and region with it, ARM shows that that region costs nothing (it can't calculate the price).

**ARM** version: v3.5
**WG** version 7.0.9-beta1+2249-223b80c
**WorldEdit** version 7.2.15

**Server version**: git-Purpur-1996 (MC: 1.20.1)*

Default ARM configuration
1. //sel poly
2. Select terrain.
3. //expand vert
4. /rg define X
5. Create sign:

1: [arm-rent]
2: 
3: X
4: 

<img width="740" alt="image" src="https://github.com/alex9849/advanced-region-market/assets/1086720/92f6755f-e3d1-4d79-a669-34d8db760f97">

**Comment by dandud100** [comment]
More information about your config and what commands you used would be good. Explain how to replicate this behavior.

**Comment by Bloodlex** [comment]
> More information about your config and what commands you used would be good. Explain how to replicate this behavior.

Hey, already added some more details

**Comment by alex9849** [comment]
The problem is that WorldGuard doesn't provide an equation to calculate the volume of a polygonal region. It's also not so easy to write a function, since that function would need to keep in mind that in minecraft there is no such thing as a continuous block. That function would need to keep in mind that only complete blocks can be part of a region. A block is part of a region or it is not. There is nothing in between.

**Comment by Bloodlex** [comment]
> The problem is that WorldGuard doesn't provide an equation to calculate the volume of a polygonal region. It's also not so easy to write a function, since that function would need to keep in mind that in minecraft there is no such thing as a continuous block. That function would need to keep in mind that only complete blocks can be part of a region. A block is part of a region or it is not. There is nothing in between.

Thanks for the reply. Did it work before because WorldGuard API was different than now? It was really nice to have plots that are not rectangular only.
