### ISSUE TITLE
Schematic selection GUI when buying/renting a region [Idea]

### ISSUE THREAD

**Issue by DerLinkman** [alex9849/advanced-region-market#16]
Hi there,
first of all thanks for your awesome plugin!
But i have a feature request/idea which is a bit unconventional (maybe):
a schematic selection gui when a player buys/rent a region (maybe toggable in per group) which allows the player to select which (house template for example) he wants to use.

This idea I just wanted to share with you, if you make something out of the idea is of course your business :D

Greetings 
DerLinkman

**Comment by alex9849** [comment]
Hmm yes. The idea looks like a cool feature. The problem ist that the plugin would need to know a lot additional stuff about these templates and the regions where the templates should be loaded in. Stuff like the ground level of the region & template, which parts of the template can be cutted if the template is to large (bottom and top), rotation, ....
I think that feature would require way to much extra configuration that you would even had to be done if you don't use any functionalities related to it.
