### ISSUE TITLE
Request: GUIUserSellWarning lore

### ISSUE THREAD

**Issue by x1p** [alex9849/advanced-region-market#18]
Shift clicking a rent sign will get you a question menu with a Yes and No button.
![Screenshot_20200705_230333](https://user-images.githubusercontent.com/28690790/86542191-ccd4bf80-bf13-11ea-836c-181e816778e0.png)

This menu blocks you from seeing the in chat warning that this will reset the region. So players miss the warning and sell their region and before they realize it, their stuff is gone.
Then they (might) read the chat and the region is already gone.

Is it possible to make the Yes button to have a lore with the appropriate warning? Just like the diamond in the `arm gui` That one has a lore with a clear warning.

**Comment by alex9849** [comment]
Yes. That shouldn't be a problem. Good idea :)
