### ISSUE TITLE
Request: RentRegionExpirationWarning placeholders

### ISSUE THREAD

**Issue by x1p** [alex9849/advanced-region-market#19]
The RentRegionExpirationWarning warns a player that a region is about to expire.
`WARNING! This RentRegion(s) will expire soon: `
But it doesn't tell the player WHEN it will expire.
The message doesn't seem to support placeholders like `%remainingtime-countdown-short%`

I would like to make a proper message like:
`WARNING! Your RentRegion %regionid% will expire in about %remainingtime-countdown-short%`

**Comment by alex9849** [comment]
Hmm yes. Your design looks better :D 
I'll implement that with the next update. :)

**Comment by alex9849** [comment]
Feature implemented. Will be published with the next release. :)
