### ISSUE TITLE
InventoryClickEvent Lagspike

### ISSUE THREAD

**Issue by x1p** [alex9849/advanced-region-market#20]
I'm not sure why but opening the gui and clicking on things leads to a severe lag spike.
Hardware, RAM or playercount is not the issue. TPS is allways 20, tick duration around 15ms/50ms.
During spike, tps drops to around 6! Spike lasts about 8 sec.
![Screenshot_20200706_011919](https://user-images.githubusercontent.com/28690790/86544463-66599c80-bf27-11ea-9cc3-1d8f0bb1bed3.png)
![Screenshot_20200706_012029](https://user-images.githubusercontent.com/28690790/86544464-66f23300-bf27-11ea-8c03-51f1753625fc.png)

**Comment by alex9849** [comment]
Okay? I don't have that issue. Do you have that problem every time you click on an item in the GUI or only if you click on a specific one?

**Comment by x1p** [comment]
I noticed the night I converted from Areashop. I had done the import, restarted, and tested the gui. Just opening the gui alone was problematic already.
I'm very cautious to try again. I have quite a strong server but a tps of 6 will not be unnoticed by players.

**Comment by alex9849** [comment]
You are able to restore your region over the gui. If someone did that, the lag could come from there. I have absolutely no idea what else could've caused that issue. If you could try to open the gui again, and click around a bit in it, that could be helpful. Maybe track the time again.

**Comment by x1p** [comment]
I don't allow players to restore and on that time I was the only one online.
I will try to reproduce it. When I'm the only one online just as a precaution.

**Comment by alex9849** [comment]
Okay. Thanks :)

**Comment by x1p** [comment]
Strangely enough: I can't reproduce it anymore.
It was the gui when seeing your own regions.

**Comment by alex9849** [comment]
Sorry for the late answer. But the problem with the Lamda method with the once per tick interval can be solved easily.  How many regions do you have? If you have a lot regions ARM has to update more regions per tick. If you increase the updateinterval of the region-signs (you can do this in the config.yml), the number of regions ARM updates per tick will get smaller and this task won't need that much time. :)

**Comment by x1p** [comment]
I have around 32 regions.
I'll try that. thnx
