### ISSUE TITLE
RentExtendMaxRentTimeExceeded

### ISSUE THREAD

**Issue by x1p** [alex9849/advanced-region-market#21]
Situation:
My regions are rented per 7days. Max Rent Time = 21days

It's 9. July today, a shop is rented till the 26. of July
Player likes to extend his rent till the 30. of July.
Instead he gets the `RentExtendMaxRentTimeExceeded` message that he is not allowed to extend his rent.

What is expected:
I would expect that he can extend the rent by another 4 days.
Meaning he should be charged 4/7*price until the 21 days are reached.

Paper 1.15.2
ARM v3.2

**Comment by alex9849** [comment]
Yes that makes sense too. I'll implement that with the next update.

**Comment by alex9849** [comment]
Feature implemented. Will be published with the next release. :)
