### ISSUE TITLE
Moving signs

### ISSUE THREAD

**Issue by Bloodlex** [alex9849/advanced-region-market#22]
Hello, I have a question: is it possible to move the rent sign for a region without resetting it so the player doesn't lose invested money and remaining rent time? Thanks for your help! :)

**Comment by alex9849** [comment]
The newest version of the plugin, that is not released yet, is going to allow you to remove all signs of a region, without deleting it.

**Comment by Bloodlex** [comment]
Thank you so much, you're the best 👍 :)
