### ISSUE TITLE
Lag and error when managing regions as owner via GUI (region with a lot of entities)

### ISSUE THREAD

**Issue by Bloodlex** [alex9849/advanced-region-market#23]
Hello,

My server works without lags and any problems except for this one situation. When I am in /arm gui and I'm clicking on "my regions" the server hangs for a couple of seconds and such exception is visible on the console:

`12.07 11:11:20 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-375 (MC: 1.15.2) ---
12.07 11:11:20 [Server] ERROR The server has not responded for 10 seconds! Creating thread dump
12.07 11:11:20 [Server] ERROR ------------------------------
12.07 11:11:20 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
12.07 11:11:20 [Server] ERROR ------------------------------
12.07 11:11:20 [Server] ERROR Current Thread: Server thread
12.07 11:11:20 [Server] ERROR PID: 26 | Suspended: false | Native: true | State: RUNNABLE
12.07 11:11:20 [Server] ERROR Stack:
12.07 11:11:20 [Server] ERROR java.net.SocketInputStream.socketRead0(Native Method)
12.07 11:11:20 [Server] ERROR java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
12.07 11:11:20 [Server] ERROR java.net.SocketInputStream.read(SocketInputStream.java:171)
12.07 11:11:20 [Server] ERROR java.net.SocketInputStream.read(SocketInputStream.java:141)
12.07 11:11:20 [Server] ERROR sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
12.07 11:11:20 [Server] ERROR sun.security.ssl.InputRecord.read(InputRecord.java:503)
12.07 11:11:20 [Server] ERROR sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:990)
12.07 11:11:20 [Server] ERROR sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:948)
12.07 11:11:20 [Server] ERROR sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
12.07 11:11:20 [Server] ERROR java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
12.07 11:11:20 [Server] ERROR java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
12.07 11:11:20 [Server] ERROR java.io.BufferedInputStream.read(BufferedInputStream.java:345)
12.07 11:11:20 [Server] ERROR sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
12.07 11:11:20 [Server] ERROR sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
12.07 11:11:20 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
12.07 11:11:20 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
12.07 11:11:20 [Server] ERROR sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
12.07 11:11:20 [Server] ERROR com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:130)
12.07 11:11:20 [Server] ERROR com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:66)
12.07 11:11:20 [Server] ERROR com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180)
12.07 11:11:20 [Server] ERROR com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:37)
12.07 11:11:20 [Server] ERROR com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173)
12.07 11:11:24 [Multicraft] Skipped 36 lines due to rate limit (30/s)
12.07 11:11:24 [Server] WARN Can't keep up! Is the server overloaded? Running 13156ms or 263 ticks behind`

Do you know maybe what can be the cause of such a lag? It happens also for other options but only in "my regions as owner" part.

**EDIT: I think I find the cause of the problem. It is EntityLimits, it is calculated and I have regions with a lot of entities. Can I disable this feature completely?**

**Comment by alex9849** [comment]
No you can disable the entitylimits. But if you remove all entitylimits placeholders, arm will not calculate them.

**Comment by Bloodlex** [comment]
I'll try to do it, thanks :) But it would be nice to have a feature to simply disable it in config :) This recalculations cause a severe lag for all of users on my server when they enter GUI

**Comment by Bloodlex** [comment]
I've just tested it a little bit and it seems to affect also regions with not many entities... do you also experience such issue? :(
