### ISSUE TITLE
Preset setup command doesn't work

### ISSUE THREAD

**Issue by Bloodlex** [alex9849/advanced-region-market#27]
Hello,

I'm not able to execute the custom setup command from preset:

`rentpreset:
  rent3:
    userrestorable: false
    autorestore: false
    inactivityReset: false
    regionKind: Default
    autoPrice: example2
    setupcommands:
    - arm setlandlord %regionid% tax`

I would like to automatically set landlord of the region to the "tax" account, but it doesn't work and it says only "Server".
Could you please take a look on that? Thank you :)

**Comment by alex9849** [comment]
Should be fixed now
