### ISSUE TITLE
Rent price (mis)calculation

### ISSUE THREAD

**Issue by x1p** [alex9849/advanced-region-market#34]
Players report that they could rent for free. In order to test this, I set up the following:
A test server was running ARM 3.2.2 on Paper 1.16.1
An area was setup to rent per 7 days and a max rent time of 20 days.
This forces to recalculate the last 6 days.

What would be expected:
Initial rent: 100 $
Extend rent: 100 $
Extend last 6 days: ~ 85.71 $

The test:
![Screenshot_20200803_170551](https://user-images.githubusercontent.com/28690790/89197184-a1dd9a00-d5ab-11ea-8e60-7ed010ab182d.png)
Findings explained:
Initial rent: 100 $
Extend rent: Is claims to cost is, 100 $, but actually 85.71 was taken from the player
Extend last 6 days: Is claims to cost is, 85,72 $, but actually 0 $ was taken from the player.
Finally the player paid 100000 - 99814,29 = 185.91 $
Should the player decide to end the rent, it receives a charge back of 285,7$.
He earned 100 $ by renting an area. Not a bad deal xd

The problem probably exists since v 3.2.1 (`Rentregions can now be extended everytime`)

**Comment by alex9849** [comment]
Oh yeah that a huge bug. Thanks for the report. Fixed it. A updating will be published in the next few minutes
