### ISSUE TITLE
arm add [worldguard-region] does not exist?

### ISSUE THREAD

**Issue by mrcoffee1026** [alex9849/advanced-region-market#37]
And this is a real problem since - although it is stated that it is easiest to use sign-linking mode, that too cannot function if regions are inside of ignored regions.  (If those regions are not ignored, sign linking will again fail with "could not tell which region to select, put one in the ignore list in your config.yml" or similar wording).  At this point this plugin is completely unusable as since the wiki isn't up to date about this command it is probably not 100% accurate with the format of the regions.yml file either, nevermind that I have no interest in generating that data by hand for 120+ regions, a single character of error anywhere and the entire plugin crashes anytime any command is run with no indication of what caused it.

**Comment by alex9849** [comment]
Can you send me your config.yml? 
In addition you could try to check if there are any syntax errors in your configuration. Just use thise site: https://yamlchecker.com/

**Comment by mrcoffee1026** [comment]
Well I don't think the config is what's having the problem since if I clear the regions file back to what it comes with( Regions: {} ), commands work fine again, just have no method of adding regions.  
[config.zip](https://github.com/alex9849/advanced-region-market/files/5043619/config.zip)

**Comment by alex9849** [comment]
Oh sorry I misunderstood you question in the beginning. I need to test that. I'll do that tomorrow :)

**Comment by alex9849** [comment]
Ok I've just tried to reproduce your issue. It didn't work (I mean reproducing the issue didn't work). All regions that i've put into the ignpre list got ignored successfully. Please make shure that all regions that overlap with the region that you want to add are added to the ignorelist of the right world. You find all regions that overlap your position by executing /rg info. There also is one version of WorldGuard that requires the region-name so match case-sensitive.

**Comment by mrcoffee1026** [comment]
From your answer, I can tell you didn't actually attempt what I did.  The problem is NOT that it will NOT ignore the region I put in the ignore list, the problem is that it WILL ignore every region that is inside of the ignored region.  However, when I redid the list I neglected to ignore one of the containing regions and it went ahead and added the containing region which revealed the true issue:  your plugin automatically can't see regions that have a "-" in their name.  As regions CAN and DO contain this character, please repair.  Note that it is still true that the command "/arm add [wg-region]" no longer exists.

**Comment by mrcoffee1026** [comment]
Huh, no... that's not the problem either... I had to click randomly many blocks before it eventually saw the region, typically it would say there was no worldguard region to select (it ALWAYS says this on the first try from what I could tell).

**Comment by mrcoffee1026** [comment]
My workaround for this problem was to use the importer tool since the old regions were defined in AreaShop.   Although that tool was designed for 1.13, it seems to have had the desired effect, linking the pre-existing signs to pre-existing regions.  There is STILL not a manual add command which is unfortunate, and using click to select seems extremely glitchy / nearly nonfunctional, just FYI.

**Comment by alex9849** [comment]
Can you make me a video where you exactly show your problem. I just don't have these issues :/

**Comment by mrcoffee1026** [comment]
maybe in a day or two, it's not that important to me, I just wanted you to be aware it was difficult to use for adding regions when the documented command to do it didn't exist and the sign linking method is rather sporadic.  Upgrading to 1.16 today so probably won't have time to do a video demonstration for a bit.

**Comment by mrcoffee1026** [comment]
I don't care about this anymore, it may or may not be resolved in 1.16.1-1.16.2.  The issue was likely that there were no blocks present inside the region I was trying to select, I'd need to test more but I have other things to deal with.  It's still true that "/arm add [worldguard-region]" is no longer a command.  As it's still in the wiki and a command at this sort simply needs to exist, might still need to fix that.
