### ISSUE TITLE
arm gui fail

### ISSUE THREAD

**Issue by mrcoffee1026** [alex9849/advanced-region-market#38]
Rent a region then access the gui with
/arm gui
When you see the list of beds interact with the first one in any way... the server locks up completely until you are disconnected.  If you have placed the fake "bed item" in your inventory it will no longer be there and you'll have been moved back in the world to wherever you were before opening the gui.  No errors or any additional information is ever printed to console, even the console is unresponsive from the moment the "bed" is interacted with, it's not even possible to get a tps response until after the player who triggered the event is kicked from the server by a timeout.

**Comment by alex9849** [comment]
Which version of the plugin are you using?

**Comment by mrcoffee1026** [comment]
3.1.2

**Comment by alex9849** [comment]
There is an option to disable player skins in the gui. The current version of spigot/paper/... somehow needs way to long the fetch skins from mojang. You can disable that in the config.yml. that should solve your problem. Btw. this problem should only happen the first time the same skin gets fetched. That may be the reason why you only got a lag the first time you opened the region menu.

**Comment by mrcoffee1026** [comment]
Why is it getting skins at all for this command?  Suddenly I feel like you're talking about a different plugin, I can find no config options regarding player skins in config.yml.

**Comment by alex9849** [comment]
If you click on a region in the region owner menu you'll should see various options like restoring the region or selling it back, but also editing the members that have access to it. And that items normally is the owners head (with his skin). Also ich you want to edit the members all heads (with skins) get loaded and displayed in the menu.

**Comment by alex9849** [comment]
You can turn of player skins in the gui in your config.yml. the option is named DisplayPlayerSkins

**Comment by mrcoffee1026** [comment]
No, that is not an option in the config, and none of that happens anyway since everything locks up the moment I click on the region.  Also, this does happen every single the time the command is attempted, no exceptions, not "just the first".

**Comment by mrcoffee1026** [comment]
This issue goes away in 1.16.1 so must be a 1.15.2 specific thing.  I don't have a 1.15.2 build to try to help you troubleshoot this anymore, what I did notice is the option you spoke of is NOT in the config anymore... and the 1.16.1 version simply shows a steve skull for the user.  There is a major delay in revealing the second gui menu page after clicking the region... for a time the bed is a moveable item that you can put in your inventory... but after this lag it snaps back out of your inventory and the menu does display instead of crashing you as it did in 1.15.2, so while it's a bit clunky this is not really the same issue.
