### ISSUE TITLE
Some regions are not recognized

### ISSUE THREAD

**Issue by LucidAPs** [alex9849/advanced-region-market#4]
Everything was working great for a long time, but suddenly a lot of regions are not recognized by the plugin. Running commands say that no region like that exists. World guard still recognize them though.

MC 1.15.2
Plugin : 2.1.5
Java 11

**Comment by alex9849** [comment]
Have you maybe unloaded a world of some regions? I regions don't get loaded on startup they will be overwritten with the next saving process of the region file.

**Comment by LucidAPs** [comment]
No the chunks that contained the plugin regions have not be unloaded, is there something i can do? Or do i have to remake the regions?

**Comment by alex9849** [comment]
Regions won't be deleted if a chunk gets unloaded. You have to unload a whole world. So it doesn't get loaded on startup.
