### ISSUE TITLE
More Custom Events for Vault specific things

### ISSUE THREAD

**Issue by Avankziar** [alex9849/advanced-region-market#45]
Hello, 
as written in the title, I would be happy to have more custom events available.
For example..: An event for buying, renting etc.

I would like to use this as interface for my Economy Plugin. Thanks in advance^^.

Avan

**Comment by alex9849** [comment]
Sorry for the late response. You should be able to use the normal buying event. The event also gives you access to the region. You can just cast it to the right class. Available classes are: Sellregion, Contractregion and Rentregion.
