### ISSUE TITLE
bug crash

### ISSUE THREAD

**Issue by demon57730** [alex9849/advanced-region-market#5]
hello here I have the latest version of spigot 1.15.2 and AdvancedRegionMarket v2.1.5, I have a very good host but when I create a panel (rental) it takes a long time (server overload) and when a player clicks on the sign to rent it crashes the server

log: https://textup.fr/427234vG

**Comment by alex9849** [comment]
That looks like a worldedit related issue. You should try to use another worldedit version or if your region is extrem big try smaller regions. :)

**Comment by demon57730** [comment]
hello thank you or actually what I saw is when we cancel the rental and therefore restore which makes crash

**Comment by alex9849** [comment]
Yes  but the arm restores its regions with worldedit and your server log looks like the problem is in worldedit.
