### ISSUE TITLE
Reset doesn't work on version 3.3

### ISSUE THREAD

**Issue by TheoRetisch1** [alex9849/advanced-region-market#51]
Resetting existing regions is completely broken after updating from v3.2.8 to v3.3. When trying to reset a region with `/arm reset <region name>` the following error appears in the log and the schematic is not loaded: https://pastebin.com/4pwJTQnE
For regions that were not sold at the time of the update, the reset works and the schematic is loaded correctly.

AdvancedRegionMarket version 3.3
FastAsyncWorldEdit version 1.16-507;bfd04e4
WorldGuard version 7.0.5-SNAPSHOT+15a0809
Tuinity version git-Tuinity-"f06591a" (MC: 1.16.4)

**Comment by alex9849** [comment]
Are you shure that this isn't a problem with WorldEdit or with FaWe? Someone from your server told me that you already had problems with some schematics in the past.

**Comment by TheoRetisch1** [comment]
I can load and paste the region schematic normally using FAWE, but `/arm reset` runs into an error. Nevertheless, you are right, something must have changed in FAWE. With the FAWE build 192 the reset problem doesn't occur. Thanks!
