### ISSUE TITLE
Area reset bug

### ISSUE THREAD

**Issue by CheddahN** [alex9849/advanced-region-market#6]
Ive made a polygonal region, and when testing I found out that the area in which it resets is outside of the selected region 
![image](https://user-images.githubusercontent.com/37481867/79091856-e8696900-7d1c-11ea-9e5b-c151902623dc.png)
For example, with the image above, the green is an example of the area that i selected, but when the area is reset by the plugin it instead resets the red area

Discord: CheddahN#1185 
if you have questions

**Comment by alex9849** [comment]
Hmm yes thats a problem. Currently arm just makes a cubic area around the selected region because I don't know how to create a polygonal are with the worldedit api. But I'll see what I can do. Maybe I find a way :)

**Comment by alex9849** [comment]
Your issue has been fixed. :)
The fix will come with the next version of the plugin
