### ISSUE TITLE
Huge bug with restoring/reseting regions

### ISSUE THREAD

**Issue by Spaex** [alex9849/advanced-region-market#61]
Minecraft Version: 1.16.5 (Paper 472)
Plugin Version: 3.3.3

Whenever a region gets reset (I think it happens since the newest world edit release 7.2.3) all items within containers are getting dropped on my server.
Short video of it:
https://youtu.be/1pQO-r5XGBU

**Comment by alex9849** [comment]
That looks more like a problem with WorldEdit. ARM completely delegates the region-restoring tasks to WorldEdit. Have you tried other WorldEdit versions?

**Comment by Spaex** [comment]
Downgraded and seemed to work fine again. Sorry then will report this bug to WorldEdit's Developers.
