### ISSUE TITLE
Bad price formatting for some locales

### ISSUE THREAD

**Issue by zankia** [alex9849/advanced-region-market#62]
Hello,

I am french and there is a problem with the price display. It prints a non breakable space instead of a blank space.
Is it possible to change this line https://github.com/alex9849/advanced-region-market/blob/master/advancedregionmarket/src/main/java/net/alex9849/arm/regions/price/Price.java#L39
to
```java
return Price.priceFormater.format(price).replaceAll("\u00A0", " ");
```
please ?

**Comment by alex9849** [comment]
Done. :)
