### ISSUE TITLE
Region groups or how to link regions?

### ISSUE THREAD

**Issue by Tomut0** [alex9849/advanced-region-market#71]
Let's say I have a house, which is not "square" type.
Is it possible to create 2 regions and make them like... one? 👀
I know, there is `/arm subregion` command, but it seems, it works only to region owners, not to server owners.

**Comment by alex9849** [comment]
Not natively. You can make 2 regions and let them overlap. If someone owns both, he should be able to build in the area that separates both regions. But the region will still be shown as 2 sperate regions in ARM.

**Comment by Tomut0** [comment]
> 
> 
> Not natively. You can make 2 regions and let them overlap. If someone owns both, he should be able to build in the area that separates both regions. But the region will still be shown as 2 sperate regions in ARM.

Isn't it too much to convert this issue as feature request? 😅
