### ISSUE TITLE
Auto and manually restore doesn't work 

### ISSUE THREAD

**Issue by Tomut0** [alex9849/advanced-region-market#73]
In the server, I have 100+ arm regions, which all auto-restorable.
And every region was restorable, until one region is not.

I did re-create a region, with removing it from ARM, it didn't help.
No errors in console.
.schem file is inside of the folder.
The rent-sign placed not in a region.

I did record a [video](https://youtu.be/H_hDb5OzeNA). 👀 
Any idea?

**Comment by alex9849** [comment]
No really. Is there any error in your log? Did you try to recreate the schematic of the region (/arm updateschematic)

**Comment by Tomut0** [comment]
> 
> 
> No really. Is there any error in your log? Did you try to recreate the schematic of the region (/arm updateschematic)

It says, it was successfully restored:
> [23:45:03] [Server thread/INFO]: Minat0_ issued server command: /arm restore house97
> [23:45:03] [Server thread/INFO]: [AdvancedRegionMarket] Region house97 has been restored! Reason: MANUALLY_BY_ADMIN 

About `/arm updateschematic`... 
![изображение](https://user-images.githubusercontent.com/42711312/127231532-58bcbe7f-da0e-49e8-924c-183189e5f1a9.png)
I'm inside of the region, but ARM says I'm not

**Comment by Tomut0** [comment]
Ok, got it.
That region was with 0 priority and it seems, it was the reason why region didn't want to be restored.
Is ARM has checking on priority? 🤔 
Anyway, the issue was solved, thanks for the response 😄
