### ISSUE TITLE
Performance issue - events

### ISSUE THREAD

**Issue by LucidAPs** [alex9849/advanced-region-market#82]
This server is running Purpur version git-Purpur-1423 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6cbba00 on ver/1.17.1)

AdvancedRegionMarket ARM v3.3.5

https://timings.pl3x.net/?id=a1085658a35c4c0a91cf0a63e10c46f6#plugins
![image](https://user-images.githubusercontent.com/42933023/140929224-8448272d-308c-47b8-bfa5-9ba131e7fc70.png)
These events need to be put on their own thread and not run in the main one, please make them async.

**Comment by alex9849** [comment]
I don't see the problem with these tasks. The first one may mdify the world and as to be put on the main thread. The other two tasks access code that hasn't been designed to be used by multiple threads, but also don't get executed very often and shouldn't really cause lags.

**Comment by LucidAPs** [comment]
> I don't see the problem with these tasks. The first one may mdify the world and as to be put on the main thread. The other two tasks access code that hasn't been designed to be used by multiple threads, but also don't get executed very often and shouldn't really cause lags.

Alright how about the sign change event?
![image](https://user-images.githubusercontent.com/42933023/141297512-c8ac32ac-9745-4415-9441-e0cd0e7d209d.png)
The more tasks , events and commands that can be moved away from the main thread the better. Please don't get defensive and try to implement some performance improvements for the community. I know it's difficult to do, but it is worth it! Especially for servers that have 60+ players, every little big can make a huge difference.

**Comment by alex9849** [comment]
The SignModifyListener also contains code that interacts with other plugins. (Like WorldEdit for creating schematics) That needs to be synchronous
