### ISSUE TITLE
Schematics exportation or download

### ISSUE THREAD

**Issue by MrDciBelia** [alex9849/advanced-region-market#84]
Hello, already, really thank you for this plugin which is really perfect, i am here because i started using the plugin on a free server (Aternos), off I took something paid and much better, i installed the plugin, but the problem is that i cannot move all my already made shematic, is there a command to retrieve the shematic that i made? (Over 100).

![1](https://user-images.githubusercontent.com/94740517/142722283-ff8642d9-6e68-4ed6-9720-e184406ba295.png)
![2](https://user-images.githubusercontent.com/94740517/142722284-0fc761d3-b002-4f53-98d8-333fe48dcb4a.png)

**Comment by alex9849** [comment]
I don't know how this works with Athernos, but downloading files from the server storage should be possible by your hoster.
