### ISSUE TITLE
Could not pass event UnsellRegionEvent to ArmShopBridge

### ISSUE THREAD

**Issue by Bloodlex** [alex9849/advanced-region-market#85]
Quickshop version: 5.0.0.16

02.12 21:48:40 [Server] ERROR Could not pass event UnsellRegionEvent to ArmShopBridge v1.2.5
02.12 21:48:40 [Server] INFO java.lang.IncompatibleClassChangeError: Method 'org.maxgamer.quickshop.api.ShopAPI org.maxgamer.quickshop.api.QuickShopAPI.getShopAPI()' must be InterfaceMethodref constant
02.12 21:48:40 [Server] INFO at net.alex9849.armshopbridge.adapters.QuickShop4Adapter.deleteShops(QuickShop4Adapter.java:35) ~[armshopbridge.jar:?]
02.12 21:48:40 [Server] INFO at net.alex9849.armshopbridge.listener.UnsellRegionListener.handleRegionReset(UnsellRegionListener.java:17) ~[armshopbridge.jar:?]
02.12 21:48:40 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1090.execute(Unknown Source) ~[?:?]
02.12 21:48:40 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1393]
02.12 21:48:40 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1393]
02.12 21:48:40 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1393]
02.12 21:48:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1393]
02.12 21:48:40 [Server] INFO at net.alex9849.arm.regions.Region.unsell(Region.java:1101) ~[advancedregionmarket-3.3.5.jar:?]
02.12 21:48:40 [Server] INFO at net.alex9849.arm.regions.CountdownRegion.unsell(CountdownRegion.java:125) ~[advancedregionmarket-3.3.5.jar:?]
02.12 21:48:40 [Server] INFO at net.alex9849.arm.regions.Region.automaticResetRegion(Region.java:1076) ~[advancedregionmarket-3.3.5.jar:?]
02.12 21:48:40 [Server] INFO at net.alex9849.arm.regions.RentRegion.updateRegion(RentRegion.java:170) ~[advancedregionmarket-3.3.5.jar:?]
02.12 21:48:40 [Server] INFO at net.alex9849.arm.regions.RegionManager$UpdateScheduler.updateNextGroup(RegionManager.java:973) ~[advancedregionmarket-3.3.5.jar:?]
02.12 21:48:40 [Server] INFO at net.alex9849.arm.regions.RegionManager.doTick(RegionManager.java:877) ~[advancedregionmarket-3.3.5.jar:?]
02.12 21:48:40 [Server] INFO at net.alex9849.arm.AdvancedRegionMarket.lambda$startup$0(AdvancedRegionMarket.java:223) ~[advancedregionmarket-3.3.5.jar:?]
02.12 21:48:40 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1393]
02.12 21:48:40 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1393]
02.12 21:48:40 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1574) ~[patched_1.17.1.jar:git-Purpur-1393]
02.12 21:48:40 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1393]
02.12 21:48:40 [Server] INFO at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1393]
02.12 21:48:40 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1393]
02.12 21:48:40 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1393]
02.12 21:48:40 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
02.12 21:48:40 [Server] INFO Region jednosc1 has been unsold! Reason: EXPIRED

**Comment by alex9849** [comment]
Oh yes. Quickshop supports ARM natively now. You can just uninstall the plugin.
