### ISSUE TITLE
Sellback UI has minor problem

### ISSUE THREAD

**Issue by ludg1e** [alex9849/advanced-region-market#89]
Hello, since a long time that I've found the bug, but didn't get a response on discord, so I'm posting it here.
The issue is that on the sellback UI (2 buttons, "yes" and "no"), the "no" button doesn't work, I've tried also deleting all the config and testing with a default config, but nothing, the problem persists. No errors on console or chat.
Here's a video showing the error, thanks

https://user-images.githubusercontent.com/77110723/151421922-e1307a6f-1c31-48bb-8bb3-b87c95bdd3a1.mp4

**Comment by alex9849** [comment]
Oh yes I've found the problem. I'll fix it
