### ISSUE TITLE
Do i need an vault plugin if i want to give out plots for free

### ISSUE THREAD

**Issue by 1456o9** [alex9849/advanced-region-market#92]
idk where to ask this but basically i want to give out plots for free so do i require an vault or economy plugin if i wanted to?

**Comment by alex9849** [comment]
Yes you need the vault plugin. Vault provides the interfaces on which ARM relies to communicate with economy plugins. If you give out your plots for free you may resign from a economy plugin. But you definitely need vault ARM isn't going to start without it.
