### ISSUE TITLE
1.18.2 support

### ISSUE THREAD

**Issue by clareiscool** [alex9849/advanced-region-market#97]
Im not a coder at all, and I'm not sure what this means, but it started happening when I upgraded my server 1.1.8.2. I'm assuming its a support issue because many of my other plugins had to be upgraded as well due to the version change. I'm running on the latest version of ARM and it was working perfectly fine prior to the update.

I have attached a screenshot of the message I am receiving from the console.

<img width="794" alt="Screenshot 2022-03-11 at 12 00 07 PM" src="https://user-images.githubusercontent.com/90165223/157799702-897ace2e-6073-4c06-b77b-5c62b00c6984.png">
l

**Comment by alex9849** [comment]
Arm is already compativle with 1.18.2 but WorldEdit doesn't support the 1.18.2 build yet. The last stable release is for 1.18.1.
I don't know why you don't get the stacktrace, but if for example arm tries to restore a region, it uses worldedit for that. If worldedit throws an error then, it will look like the error came from arm.

The only thing you can do is wait for a stable WorldEdit build that supports the 1.18.2 version.
I mean you should wait for a stable version. But you could also use an experimental build. For example this one here:
https://builds.enginehub.org/job/worldedit/19838

But keep in mind that this isn't recommended and using experimental builds could cause serious harm to your server if you are unlucky.
